import CraftChart from "../components/CraftChart";
import ImageWithFallback from "../components/ImageWithFallback";
import OrderAnalytics from "../components/OrderAnalytics";
import CertificatePanel from "../components/CertificatePanel";
import ProfileEditor from "../components/ProfileEditor";
import { useState } from "react";
import { Link } from "react-router";
import QRCode from "qrcode";
import { useApp } from "../context/AppContext";
import { getStore, mutate, updateOrderStatus } from "../data/store";
import type { Role, Order } from "../data/types";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
const money = (n: number) => Number(n || 0).toLocaleString("es-MX", { style: "currency", currency: "MXN" });
const labels: Record<string, string> = { paid: "Pagado", pending_payment: "Pago pendiente", preparing: "En preparación", shipped: "Enviado", delivered: "Entregado", cancelled: "Cancelado", return_requested: "Devolución solicitada", refunded: "Reembolsado", pending: "Pendiente", published: "Publicado", rejected: "Rechazado", paused: "Pausado", active: "Activo", suspended: "Suspendido", approved: "Aprobado" };
export default function LiveDashboard({ role }: { role: Role }) {
 const { user, logout, unreadCount } = useApp(); const store = getStore(); const [tab, setTab] = useState("Resumen"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
 const [subject, setSubject] = useState(""); const [description, setDescription] = useState("");
 const [qrImage, setQrImage] = useState("");
 if (!user) return <div className="p-12"><Link to="/login" className="btn-primary">Iniciar sesión</Link></div>;
 if (user.role !== role) return <div className="p-12">No tienes acceso a este panel.</div>;
 const profile = store.producer_profiles.find(p => p.user_id === user.id);
 const products = role === "producer" ? store.products.filter(p => p.producer_id === profile?.id) : store.products;
 const orders = store.orders.filter(o => (!from || o.created_at.slice(0, 10) >= from) && (!to || o.created_at.slice(0, 10) <= to));
 const successful = orders.filter(o => ["paid", "preparing", "shipped", "delivered", "return_requested"].includes(o.status));
 const sum = (key: "subtotal" | "platform_commission" | "producer_net" | "processing_cost" | "total") => successful.reduce((s, o) => s + Number(o[key] || 0), 0);
 const months: Record<string, number> = {}; successful.forEach(o => { const m = o.created_at.slice(0, 7); months[m] = (months[m] || 0) + Number(role === "consumer" ? o.total : o.subtotal); });
 const tabs = ["Resumen", "Pedidos", "Pagos", "Estadísticas", "Notificaciones", "Soporte", "Perfil", ...(role === "producer" ? ["Productos", "Certificados", "QR", "Consentimientos"] : []), ...(role === "admin" ? ["Usuarios", "Productores", "Productos", "Certificados", "Consentimientos", "Reseñas", "Bitácora"] : []), ...(role === "consumer" ? ["Favoritos"] : [])];
 async function action(path: string, method: string, body?: unknown) { setBusy(true); setError(""); try { await mutate(path, method, body); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 function exportCSV() { const columns = role === "consumer" ? ["order_number", "status", "subtotal", "shipping", "total"] : role === "producer" ? ["order_number", "status", "subtotal", "platform_commission", "producer_net"] : ["order_number", "status", "subtotal", "platform_commission", "processing_cost", "producer_net"]; const quote = (value: unknown) => '"' + String(value ?? "").replace(/^[=+@-]/, "'").replaceAll('"', '""') + '"'; const text = [columns.join(","), ...orders.map(o => columns.map(k => quote((o as unknown as Record<string, unknown>)[k])).join(","))].join("\r\n"); const url = URL.createObjectURL(new Blob(["\uFEFF" + text], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "pedidos-voces.csv"; a.click(); URL.revokeObjectURL(url); }
 async function review(o: Order, product_id: string) { const rating = Number(prompt("Calificación del 1 al 5:")); const comment = prompt("Reseña:"); if (comment) await action("reviews", "POST", { order_id: o.id, product_id, rating, comment }); }
 const button = (label: string, fn: () => unknown) => <button disabled={busy} className="btn-secondary text-xs mr-2 mb-2" onClick={() => void fn()}>{label}</button>;
 const roleTitle=role === "admin"?"El pulso de Voces":role === "producer"?"Tu taller, tu historia":"Tu rincón de artesanías";
 const symbols:Record<string,string>={Resumen:"◈",Pedidos:"▣",Pagos:"$",Estadísticas:"▥",Notificaciones:"◉",Soporte:"?",Perfil:"◎",Favoritos:"♡",Productos:"◇",Usuarios:"♙",Productores:"⌂",Certificados:"✓",Consentimientos:"☷",QR:"▦",Reseñas:"☆",Bitácora:"≡"};
 return <div className={`dashboard-shell role-${role}`}><div className="dashboard-layout"><aside className="dashboard-sidebar"><Link to="/" className="sidebar-brand"><img src="/design/mascota.png" alt="Mascota de Voces"/><div><strong>Voces de mi Tierra</strong><span>{role === "admin"?"Administración":role === "producer"?"Mi taller":"Mis descubrimientos"}</span></div></Link><nav aria-label="Secciones del panel">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} aria-current={tab===t?"page":undefined} className={`dashboard-nav ${tab===t?"selected":""}`}><span aria-hidden="true">{symbols[t]}</span><b>{t}</b>{t==="Notificaciones"&&unreadCount>0&&<small>{unreadCount}</small>}{t==="Certificados"&&(store.certificates||[]).some(c=>c.status==="pending")&&<small>{store.certificates.filter(c=>c.status==="pending").length}</small>}</button>)}</nav><div className="sidebar-footer"><p>Hecho con alma en Quintana Roo</p>{button("Cerrar sesión",logout)}</div></aside><div className="dashboard-main"><header className="dashboard-welcome"><div><span className="eyebrow">{roleTitle}</span><h1>Hola, <span translate="no">{user.name}</span></h1><p>{role === "consumer"?"Cada compra conecta contigo y con quien la crea.":role === "producer"?"Todo lo que necesitas para acompañar tus piezas.":"Acompaña a tu comunidad y organiza cada detalle."}</p></div>{user.avatar_url?<ImageWithFallback src={user.avatar_url} alt="Mi foto de perfil"/>:<span className="welcome-initial" translate="no">{user.name.charAt(0)}</span>}</header><div className="dashboard-section-heading"><h2>{tab}</h2><span className="demo-subtle">Pagos de demostración · Sin cargos</span></div>
 {error && <p role="alert" className="bg-red-100 p-4 mb-4">{error}</p>}{busy && <p role="status">Guardando…</p>}
 <div className="dashboard-content">
 {(tab === "Resumen" || tab === "Estadísticas" || tab === "Pedidos") && <div className="dashboard-filters flex flex-wrap gap-3 mb-5"><label>Desde<input type="date" className="input-field" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input type="date" className="input-field" value={to} onChange={e => setTo(e.target.value)} /></label>{button("Descargar CSV", exportCSV)}</div>}
 {(tab === "Resumen" || tab === "Estadísticas") && <><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">{[{ label: "Pedidos", value: orders.length }, { label: role === "consumer" ? "Compras" : "Venta de productos", value: money(sum(role === "consumer" ? "total" : "subtotal")) }, ...(role !== "consumer" ? [{ label: "Comisión 10%", value: money(sum("platform_commission")) }, { label: "Neto de productores", value: money(sum("producer_net")) }] : [{ label: "Favoritos", value: store.favorites.length }, { label: "Entregados", value: orders.filter(o => o.status === "delivered").length }]), ...(role === "admin" ? [{ label: "Costo de procesamiento", value: money(sum("processing_cost")) }, { label: "Margen preliminar", value: money(sum("platform_commission") - sum("processing_cost")) }, { label: "Usuarios", value: store.users.length }, { label: "Pendientes", value: products.filter(p => p.status === "pending").length }] : [])].map(x => <div key={x.label} className="metric-card"><p>{x.label}</p><strong className="text-xl">{x.value}</strong></div>)}</div><div className="chart-title"><ImageWithFallback src={products[0]?.featured_image || "/demo/productos/cuenco.png"} alt=""/><div><span className="eyebrow">El ritmo de tus piezas</span><h2 className="font-bold">{role === "consumer" ? "Gasto en compras por mes" : "Ventas de productos por mes"}</h2></div></div>{Object.keys(months).length ? <CraftChart data={Object.keys(months).sort().map(month=>({name:new Date(`${month}-02T12:00:00`).toLocaleDateString("es-MX",{month:"short",year:"2-digit"}),value:months[month]}))} currency/> : <p>Aún no hay compras en este periodo.</p>}<OrderAnalytics orders={orders} payments={store.payments} products={store.products} profiles={store.producer_profiles} role={role}/>{tab === "Resumen" && <section className="mt-6"><h2 className="font-bold mb-3">{role === "consumer" ? "Mis compras recientes" : "Pedidos recientes"}</h2>{[...orders].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5).map(o=><p key={o.id} className="dashboard-record">{o.order_number} · {labels[o.status]} · {money(o.total)}</p>)}{button("Ver pedidos y direcciones",()=>setTab("Pedidos"))}</section>}{role === "producer" && <Link className="btn-primary mt-5" to="/productor/nueva-publicacion">Publicar pieza</Link>}</>}
 {tab === "Pedidos" && <div className="space-y-4">{!orders.length && <p>No hay pedidos.</p>}{orders.map(o => <article key={o.id} className={`order-card status-${o.status}`}><div className="order-heading"><h2 className="font-bold" translate="no">{o.order_number}</h2><span className={`status-pill status-${o.status}`}>{labels[o.status]}</span></div><div className="order-meta"><strong translate="no">{money(o.total)}</strong><span>{o.created_at.slice(0,10)}</span></div><p>Envío: {o.carrier || "Por registrar"} · Guía: {o.tracking_number || "Pendiente"}</p>{o.tracking_number && button("Copiar guía", () => navigator.clipboard.writeText(o.tracking_number!))}<div className="order-pieces">{o.items.map(i=>{const product=products.find(p=>p.id===i.product_id);return <div key={i.product_id} className="order-piece"><ImageWithFallback src={product?.featured_image} alt={product?.name}/><span>{product?.name||i.product_id}</span><b>× {i.quantity}</b></div>})}</div><div className="shipping-route"><div><small>Origen · Taller</small><p translate="no">{o.origin_address || "El taller debe completar su dirección de envío."}</p></div><span aria-hidden="true">→</span><div><small>Destino · Comprador</small><p translate="no">{o.consumer_address}</p></div></div>

 {role === "producer" && o.status === "paid" && button("Preparar", () => updateOrderStatus(o.id, "preparing"))}{role === "producer" && o.status === "preparing" && button("Registrar envío", () => updateOrderStatus(o.id, "shipped"))}
 {role === "consumer" && o.status === "shipped" && button("Confirmar recepción", () => action(`orders/${o.id}`, "PATCH", { status: "delivered" }))}{role === "consumer" && o.status === "delivered" && <>{button("Solicitar devolución", () => action(`orders/${o.id}`, "PATCH", { status: "return_requested" }))}{o.items.map(i => <span key={i.product_id}>{button("Reseñar pieza", () => review(o, i.product_id))}</span>)}</>}{role === "consumer" && o.status === "pending_payment" && button("Cancelar", () => action(`orders/${o.id}`, "PATCH", { status: "cancelled" }))}
 {role === "admin" && ["paid", "preparing", "return_requested"].includes(o.status) && button("Reembolsar", () => confirm("¿Reembolsar este pedido simulado?") && action(`orders/${o.id}`, "PATCH", { status: "refunded" }))}
 </article>)}</div>}
 {tab === "Productos" && <>{role === "producer" && <Link className="btn-primary mb-4" to="/productor/nueva-publicacion">Nueva publicación</Link>}{products.map(p => <article key={p.id} className="dashboard-record"><div className="record-product"><ImageWithFallback src={p.featured_image} alt={p.name}/><div><h2 className="font-bold">{p.name}</h2><span className={`status-pill status-${p.status}`}>{labels[p.status]}</span></div></div><p>{money(p.price)} · Stock {p.stock}</p>{p.certificate_status&&<p className="text-sm my-2">Certificado: {labels[p.certificate_status]} · Revisa la sección Certificados.</p>}{role === "admin" ? <>{button("Publicar", () => action(`products/${p.id}`, "PATCH", { status: "published" }))}{button("Rechazar", () => action(`products/${p.id}`, "PATCH", { status: "rejected" }))}</> : button("Editar precio y stock", () => { const price = Number(prompt("Precio:", String(p.price))); const stock = Number(prompt("Stock:", String(p.stock))); return action(`products/${p.id}`, "PATCH", { price, stock, status: "pending" }); })}{button("Pausar", () => action(`products/${p.id}`, "PATCH", { status: "paused" }))}</article>)}</>}
 {tab === "Usuarios" && store.users.map(u => <article key={u.id} className="dashboard-record"><p>{u.name} · {u.email} · {u.role} · {labels[u.status]}</p>{u.id !== user.id && button(u.status === "active" ? "Suspender" : "Activar", () => action(`users/${u.id}`, "PATCH", { status: u.status === "active" ? "suspended" : "active" }))}</article>)}
 {tab === "Productores" && store.producer_profiles.map(p => <article key={p.id} className="dashboard-record"><h2>{p.workshop_name} · {labels[p.authorization_status]}</h2>{button("Aprobar", () => action(`producers/${p.id}`, "PATCH", { authorization_status: "approved" }))}{button("Rechazar", () => action(`producers/${p.id}`, "PATCH", { authorization_status: "rejected" }))}</article>)}
 {tab === "Pagos" && store.payments.map(p => <p key={p.id} className="dashboard-record">{store.orders.find(o=>o.id===p.order_id)?.order_number || p.order_id} · {p.method === "card" ? "Tarjeta" : p.method === "paypal" ? "PayPal" : p.method === "transfer" ? "Transferencia" : "Pendiente"} · {labels[p.status] || p.status} · {money(p.amount)} · {p.created_at.slice(0,10)}</p>)}
 {tab === "Notificaciones" && <>{button("Marcar como leídas", () => action("notifications/read", "POST"))}{store.notifications.map(n => <article key={n.id} className="dashboard-record"><strong>{n.title}{!n.read && " · Nueva"}</strong><p>{n.message}</p>{n.type === "certificate" && button("Abrir certificados",()=>setTab("Certificados"))}</article>)}</>}
 {tab === "Soporte" && <><form className="mb-6" onSubmit={e => { e.preventDefault(); void action("tickets", "POST", { subject, description }); }}><label>Asunto<input required maxLength={220} className="input-field mb-3" value={subject} onChange={e => setSubject(e.target.value)} /></label><label>Descripción<textarea required className="input-field mb-3" value={description} onChange={e => setDescription(e.target.value)} /></label><button disabled={busy} className="btn-primary">Crear solicitud</button></form>{store.support_tickets.map(t => <article key={t.id} className="dashboard-record"><h2>{t.subject} · {t.status}</h2><p>{t.description}</p>{role === "admin" && ["in_progress", "resolved", "closed"].map(status => <span key={status}>{button(status, () => action(`tickets/${t.id}`, "PATCH", { status }))}</span>)}</article>)}</>}
 {tab === "Certificados" && <CertificatePanel role={role} />}
 {tab === "Perfil" && <ProfileEditor />}
 {tab === "Consentimientos" && store.consents.map(c => <article key={c.id} className="dashboard-record"><p>{products.find(p => p.id === c.product_id)?.name || c.product_id} · {c.revoked_at ? "Retirado" : "Vigente"} · {c.expires_at || "Sin fecha de vencimiento"}</p>{role === "producer" && !c.revoked_at && button("Retirar consentimiento", () => confirm("Se pausará la publicación. ¿Continuar?") && action(`consents/${c.id}`, "DELETE"))}</article>)}
 {tab === "QR" && <>{store.qr_codes.filter(q => products.some(p => p.id === q.product_id)).map(q => <article key={q.id} className="dashboard-record"><p>{products.find(p => p.id === q.product_id)?.name} · {q.scans} escaneos</p><a href={q.public_url}>{q.public_url}</a><div className="mt-3">{button("Ver / descargar PNG", async () => setQrImage(await QRCode.toDataURL(q.public_url, { width: 600, margin: 2 })))}{button(q.active ? "Desactivar" : "Activar", () => action(`qr/${q.id}`, "PATCH", { active: !q.active }))}{button("Imprimir", () => window.print())}</div></article>)}{qrImage && <div className="mt-4"><img src={qrImage} alt="Código QR del producto" className="w-64" /><a className="btn-primary" href={qrImage} download="qr-voces.png">Descargar PNG</a></div>}</>}
 {tab === "Favoritos" && <Link className="btn-primary" to="/favoritos">Abrir mis favoritos</Link>}
 {tab === "Reseñas" && store.reviews.map(r => <article key={r.id} className="dashboard-record"><p>{r.consumer_name} · {r.rating}/5 · {r.comment}</p>{button("Publicar", () => action(`reviews/${r.id}`, "PATCH", { status: "published" }))}{button("Rechazar", () => action(`reviews/${r.id}`, "PATCH", { status: "rejected" }))}</article>)}
 {tab === "Bitácora" && store.audit_logs.map(l => <p className="py-2" key={l.id}>{l.created_at} · {l.action} · {l.target_id}</p>)}
 </div></div></div></div>;
}
