import CertificatePanel from "../components/CertificatePanel";
import ProfileEditor from "../components/ProfileEditor";
import { useState } from "react";
import { Link } from "react-router";
import QRCode from "qrcode";
import { useApp } from "../context/AppContext";
import { getStore, mutate, updateOrderStatus } from "../data/store";
import type { Role, Order } from "../data/types";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
const money = (n: number) => Number(n || 0).toLocaleString("es-MX", { style: "currency", currency: "MXN" });
const labels: Record<string, string> = { paid: "Pagado", pending_payment: "Pago pendiente", preparing: "En preparación", shipped: "Enviado", delivered: "Entregado", cancelled: "Cancelado", return_requested: "Devolución solicitada", refunded: "Reembolsado", pending: "Pendiente", published: "Publicado", rejected: "Rechazado", paused: "Pausado", active: "Activo", suspended: "Suspendido", approved: "Aprobado" };
export default function LiveDashboard({ role }: { role: Role }) {
 const { user, logout, unreadCount } = useApp(); const store = getStore(); const [tab, setTab] = useState("Resumen"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
 const [subject, setSubject] = useState(""); const [description, setDescription] = useState("");
 const [qrImage, setQrImage] = useState("");
 if (!user) return <div className="p-12"><Link to="/login" className="btn-primary">Iniciar sesión</Link></div>;
 if (user.role !== role) return <div className="p-12">No tienes acceso a este panel.</div>;
 const profile = store.producer_profiles.find(p => p.user_id === user.id);
 const products = role === "producer" ? store.products.filter(p => p.producer_id === profile?.id) : store.products;
 const orders = store.orders.filter(o => (!from || o.created_at.slice(0, 10) >= from) && (!to || o.created_at.slice(0, 10) <= to));
 const successful = orders.filter(o => ["paid", "preparing", "shipped", "delivered", "return_requested"].includes(o.status));
 const sum = (key: "subtotal" | "platform_commission" | "producer_net" | "processing_cost" | "total") => successful.reduce((s, o) => s + Number(o[key] || 0), 0);
 const months: Record<string, number> = {}; successful.forEach(o => { const m = o.created_at.slice(0, 7); months[m] = (months[m] || 0) + o.subtotal; });
 const tabs = ["Resumen", "Pedidos", "Estadísticas", "Notificaciones", "Soporte", "Perfil", ...(role === "producer" ? ["Productos", "Certificados", "QR", "Consentimientos"] : []), ...(role === "admin" ? ["Usuarios", "Productores", "Productos", "Certificados", "Pagos", "Consentimientos", "Reseñas", "Bitácora"] : []), ...(role === "consumer" ? ["Favoritos"] : [])];
 async function action(path: string, method: string, body?: unknown) { setBusy(true); setError(""); try { await mutate(path, method, body); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 function exportCSV() { const columns = role === "consumer" ? ["order_number", "status", "subtotal", "shipping", "total"] : role === "producer" ? ["order_number", "status", "subtotal", "platform_commission", "producer_net"] : ["order_number", "status", "subtotal", "platform_commission", "processing_cost", "producer_net"]; const quote = (value: unknown) => '"' + String(value ?? "").replace(/^[=+@-]/, "'").replaceAll('"', '""') + '"'; const text = [columns.join(","), ...orders.map(o => columns.map(k => quote((o as unknown as Record<string, unknown>)[k])).join(","))].join("\r\n"); const url = URL.createObjectURL(new Blob(["\uFEFF" + text], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "pedidos-voces.csv"; a.click(); URL.revokeObjectURL(url); }
 async function review(o: Order, product_id: string) { const rating = Number(prompt("Calificación del 1 al 5:")); const comment = prompt("Reseña:"); if (comment) await action("reviews", "POST", { order_id: o.id, product_id, rating, comment }); }
 const button = (label: string, fn: () => unknown) => <button disabled={busy} className="btn-secondary text-xs mr-2 mb-2" onClick={() => void fn()}>{label}</button>;
 return <div className="bg-[#F5EFE4] min-h-screen p-4 sm:p-8"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap gap-4 justify-between mb-4"><h1 className="text-2xl font-bold">Panel · {user.name}</h1>{button("Cerrar sesión", logout)}</div><p className="text-xs text-[#6B6763] mb-5">Proyecto de demostración · No se realizan cargos.</p>
 <nav className="flex flex-wrap gap-2 mb-6" aria-label="Secciones del panel">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={tab === t ? "btn-primary" : "btn-secondary"}>{t}{t === "Notificaciones" && unreadCount > 0 ? ` (${unreadCount})` : ""}{t === "Certificados" && (store.certificates||[]).some(c=>c.status === "pending") ? ` (${(store.certificates||[]).filter(c=>c.status === "pending").length})` : ""}</button>)}</nav>
 {error && <p role="alert" className="bg-red-100 p-4 mb-4">{error}</p>}{busy && <p role="status">Guardando…</p>}
 <div className="bg-white rounded-xl p-5">
 {(tab === "Resumen" || tab === "Estadísticas" || tab === "Pedidos") && <div className="flex flex-wrap gap-3 mb-5"><label>Desde<input type="date" className="input-field" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input type="date" className="input-field" value={to} onChange={e => setTo(e.target.value)} /></label>{button("Descargar CSV", exportCSV)}</div>}
 {(tab === "Resumen" || tab === "Estadísticas") && <><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">{[{ label: "Pedidos", value: orders.length }, { label: role === "consumer" ? "Compras" : "Venta de productos", value: money(sum(role === "consumer" ? "total" : "subtotal")) }, ...(role !== "consumer" ? [{ label: "Comisión 10%", value: money(sum("platform_commission")) }, { label: "Neto de productores", value: money(sum("producer_net")) }] : [{ label: "Favoritos", value: store.favorites.length }, { label: "Entregados", value: orders.filter(o => o.status === "delivered").length }]), ...(role === "admin" ? [{ label: "Costo de procesamiento", value: money(sum("processing_cost")) }, { label: "Margen preliminar", value: money(sum("platform_commission") - sum("processing_cost")) }, { label: "Usuarios", value: store.users.length }, { label: "Pendientes", value: products.filter(p => p.status === "pending").length }] : [])].map(x => <div key={x.label} className="p-4 bg-[#F5EFE4] rounded-lg"><p>{x.label}</p><strong className="text-xl">{x.value}</strong></div>)}</div><h2 className="font-bold mb-3">Importe de productos por mes</h2>{Object.keys(months).length ? <div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={Object.keys(months).sort().map(month => ({ month, ventas: months[month] }))}><XAxis dataKey="month" /><YAxis /><Tooltip /><Bar dataKey="ventas" fill="#315C4C" /></BarChart></ResponsiveContainer></div> : <p>Aún no hay compras en este periodo.</p>}{role === "producer" && <Link className="btn-primary mt-5" to="/productor/nueva-publicacion">Publicar pieza</Link>}</>}
 {tab === "Pedidos" && <div className="space-y-4">{!orders.length && <p>No hay pedidos.</p>}{orders.map(o => <article key={o.id} className="border p-4 rounded-lg"><h2 className="font-bold">{o.order_number} · {labels[o.status]}</h2><p>{money(o.total)} · {o.created_at.slice(0, 10)}</p><p>Envío: {o.carrier || "Por registrar"} · Guía: {o.tracking_number || "Pendiente"}</p>{o.tracking_number && button("Copiar guía", () => navigator.clipboard.writeText(o.tracking_number!))}<p className="my-2">{o.items.map(i => `${products.find(p => p.id === i.product_id)?.name || i.product_id} × ${i.quantity}`).join(" · ")}</p><p className="mb-3">Destino: {o.consumer_address}</p>
 {role === "producer" && o.status === "paid" && button("Preparar", () => updateOrderStatus(o.id, "preparing"))}{role === "producer" && o.status === "preparing" && button("Registrar envío", () => updateOrderStatus(o.id, "shipped"))}
 {role === "consumer" && o.status === "shipped" && button("Confirmar recepción", () => action(`orders/${o.id}`, "PATCH", { status: "delivered" }))}{role === "consumer" && o.status === "delivered" && <>{button("Solicitar devolución", () => action(`orders/${o.id}`, "PATCH", { status: "return_requested" }))}{o.items.map(i => <span key={i.product_id}>{button("Reseñar pieza", () => review(o, i.product_id))}</span>)}</>}{role === "consumer" && o.status === "pending_payment" && button("Cancelar", () => action(`orders/${o.id}`, "PATCH", { status: "cancelled" }))}
 {role === "admin" && ["paid", "preparing", "return_requested"].includes(o.status) && button("Reembolsar", () => confirm("¿Reembolsar este pedido simulado?") && action(`orders/${o.id}`, "PATCH", { status: "refunded" }))}
 </article>)}</div>}
 {tab === "Productos" && <>{role === "producer" && <Link className="btn-primary mb-4" to="/productor/nueva-publicacion">Nueva publicación</Link>}{products.map(p => <article key={p.id} className="border-b py-4"><h2 className="font-bold">{p.name} · {labels[p.status]}</h2><p>{money(p.price)} · Stock {p.stock}</p>{p.certificate_status&&<p className="text-sm my-2">Certificado: {labels[p.certificate_status]} · Revisa la sección Certificados.</p>}{role === "admin" ? <>{button("Publicar", () => action(`products/${p.id}`, "PATCH", { status: "published" }))}{button("Rechazar", () => action(`products/${p.id}`, "PATCH", { status: "rejected" }))}</> : button("Editar precio y stock", () => { const price = Number(prompt("Precio:", String(p.price))); const stock = Number(prompt("Stock:", String(p.stock))); return action(`products/${p.id}`, "PATCH", { price, stock, status: "pending" }); })}{button("Pausar", () => action(`products/${p.id}`, "PATCH", { status: "paused" }))}</article>)}</>}
 {tab === "Usuarios" && store.users.map(u => <article key={u.id} className="border-b py-4"><p>{u.name} · {u.email} · {u.role} · {labels[u.status]}</p>{u.id !== user.id && button(u.status === "active" ? "Suspender" : "Activar", () => action(`users/${u.id}`, "PATCH", { status: u.status === "active" ? "suspended" : "active" }))}</article>)}
 {tab === "Productores" && store.producer_profiles.map(p => <article key={p.id} className="border-b py-4"><h2>{p.workshop_name} · {labels[p.authorization_status]}</h2>{button("Aprobar", () => action(`producers/${p.id}`, "PATCH", { authorization_status: "approved" }))}{button("Rechazar", () => action(`producers/${p.id}`, "PATCH", { authorization_status: "rejected" }))}</article>)}
 {tab === "Pagos" && store.payments.map(p => <p key={p.id} className="border-b py-3">{p.sandbox_transaction_id} · {p.status} · {money(p.amount)}</p>)}
 {tab === "Notificaciones" && <>{button("Marcar como leídas", () => action("notifications/read", "POST"))}{store.notifications.map(n => <article key={n.id} className="border-b py-4"><strong>{n.title}{!n.read && " · Nueva"}</strong><p>{n.message}</p>{n.type === "certificate" && button("Abrir certificados",()=>setTab("Certificados"))}</article>)}</>}
 {tab === "Soporte" && <><form className="mb-6" onSubmit={e => { e.preventDefault(); void action("tickets", "POST", { subject, description }); }}><label>Asunto<input required maxLength={220} className="input-field mb-3" value={subject} onChange={e => setSubject(e.target.value)} /></label><label>Descripción<textarea required className="input-field mb-3" value={description} onChange={e => setDescription(e.target.value)} /></label><button disabled={busy} className="btn-primary">Crear solicitud</button></form>{store.support_tickets.map(t => <article key={t.id} className="border-b py-4"><h2>{t.subject} · {t.status}</h2><p>{t.description}</p>{role === "admin" && ["in_progress", "resolved", "closed"].map(status => <span key={status}>{button(status, () => action(`tickets/${t.id}`, "PATCH", { status }))}</span>)}</article>)}</>}
 {tab === "Certificados" && <CertificatePanel role={role} />}
 {tab === "Perfil" && <ProfileEditor />}
 {tab === "Consentimientos" && store.consents.map(c => <article key={c.id} className="border-b py-4"><p>{products.find(p => p.id === c.product_id)?.name || c.product_id} · {c.revoked_at ? "Retirado" : "Vigente"} · {c.expires_at || "Sin fecha de vencimiento"}</p>{role === "producer" && !c.revoked_at && button("Retirar consentimiento", () => confirm("Se pausará la publicación. ¿Continuar?") && action(`consents/${c.id}`, "DELETE"))}</article>)}
 {tab === "QR" && <>{store.qr_codes.filter(q => products.some(p => p.id === q.product_id)).map(q => <article key={q.id} className="border-b py-4"><p>{products.find(p => p.id === q.product_id)?.name} · {q.scans} escaneos</p><a href={q.public_url}>{q.public_url}</a><div className="mt-3">{button("Ver / descargar PNG", async () => setQrImage(await QRCode.toDataURL(q.public_url, { width: 600, margin: 2 })))}{button(q.active ? "Desactivar" : "Activar", () => action(`qr/${q.id}`, "PATCH", { active: !q.active }))}{button("Imprimir", () => window.print())}</div></article>)}{qrImage && <div className="mt-4"><img src={qrImage} alt="Código QR del producto" className="w-64" /><a className="btn-primary" href={qrImage} download="qr-voces.png">Descargar PNG</a></div>}</>}
 {tab === "Favoritos" && <Link className="btn-primary" to="/favoritos">Abrir mis favoritos</Link>}
 {tab === "Reseñas" && store.reviews.map(r => <article key={r.id} className="border-b py-4"><p>{r.consumer_name} · {r.rating}/5 · {r.comment}</p>{button("Publicar", () => action(`reviews/${r.id}`, "PATCH", { status: "published" }))}{button("Rechazar", () => action(`reviews/${r.id}`, "PATCH", { status: "rejected" }))}</article>)}
 {tab === "Bitácora" && store.audit_logs.map(l => <p className="py-2" key={l.id}>{l.created_at} · {l.action} · {l.target_id}</p>)}
 </div></div></div>;
}
