import { useState } from "react";
import { Link } from "react-router";
import { useApp } from "../context/AppContext";
import { api } from "../data/api";
import { mutate } from "../data/store";
const steps = ["Información", "Fotografías", "Materiales", "Técnica y proceso", "Historia", "Precio y envío", "Consentimiento", "Revisión"];
const categories = ["Textiles y bordados", "Madera", "Fibras naturales", "Cerámica", "Joyería artesanal", "Decoración", "Accesorios"];
export default function NewListing() {
 const { user } = useApp(); const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState("");
 const [form, setForm] = useState({ name: "", description: "", category: categories[0], materials: "", technique: "", process: "", history: "", production_time: "", price: "", stock: "1", package_weight: "0.5", package_dimensions: "30x20x10", video_url: "", expires_at: "" });
 const [gallery, setGallery] = useState<string[]>([]); const [consents, setConsents] = useState<Record<string, boolean>>({});
 const field = (key: keyof typeof form, label: string, type = "text") => <label className="block mb-4 text-sm">{label}<input className="input-field mt-1" type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>;
 async function upload(files: FileList | null, video = false) { if (!files) return; setBusy(true); setError(""); try { const urls: string[] = []; for (const file of Array.from(files)) { const data = new FormData(); data.append("file", file); urls.push((await api("uploads", "POST", data)).url); } if (video) setForm(f => ({ ...f, video_url: urls[0] })); else setGallery(g => [...g, ...urls].slice(0, 8)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 async function next() { setError(""); if (step === 0 && (!form.name.trim() || !form.description.trim())) { setError("Nombre y descripción requeridos."); return; } if (step === 1 && !gallery.length) { setError("Carga al menos una fotografía."); return; } if (step === 2 && !form.materials.trim()) { setError("Indica los materiales."); return; } if (step === 3 && !form.technique.trim()) { setError("Indica la técnica."); return; } if (step === 5 && (!(Number(form.price) > 0) || !Number.isInteger(Number(form.stock)) || Number(form.stock) < 0)) { setError("Revisa precio y existencias."); return; } if (step < 7) { setStep(step + 1); return; } setBusy(true); try { await mutate("products", "POST", { ...form, expires_at: form.expires_at || null, materials: form.materials.split(",").map(x => x.trim()).filter(Boolean), gallery, consents }); setDone(true); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 if (user?.role !== "producer") return <div className="p-12">Acceso exclusivo para productores.</div>;
 if (done) return <div className="p-12 text-center"><h1>Publicación guardada y enviada a revisión.</h1><Link className="btn-primary mt-4" to="/productor/dashboard">Ir a mi panel</Link></div>;
 return <div className="bg-[#F5EFE4] py-10 px-4"><div className="max-w-xl mx-auto bg-white p-6 rounded-xl"><h1 className="text-2xl font-bold mb-5">Publicar una pieza</h1><p className="mb-4">Paso {step + 1} de 8: {steps[step]}</p><progress value={step + 1} max={8} className="w-full mb-6" />
 {step === 0 && <>{field("name", "Nombre de la pieza")}{field("description", "Descripción")}</>}
 {step === 1 && <><p className="mb-4">Usa luz natural, fondo limpio y fotografías del frente, reverso y detalles. Máximo 8 imágenes.</p><input aria-label="Fotografías" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e => void upload(e.target.files)} /><div className="grid grid-cols-3 gap-3 mt-4">{gallery.map((url, i) => <div key={url}><img alt={`Fotografía ${i + 1}`} src={url} className="w-full h-24 object-cover" /><button onClick={() => setGallery(g => g.filter((_, j) => i !== j))}>Eliminar</button><button className="ml-2" onClick={() => setGallery(g => [g[i], ...g.filter((_, j) => i !== j)])}>Principal</button></div>)}</div></>}
 {step === 2 && <><label>Categoría<select className="input-field mb-4" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.map(c => <option key={c}>{c}</option>)}</select></label>{field("materials", "Materiales separados por comas")}</>}
 {step === 3 && <>{field("technique", "Técnica")}{field("process", "Proceso de elaboración")}{field("production_time", "Tiempo de elaboración")}<label>Video opcional<input className="block mb-4" type="file" accept="video/mp4,video/webm" onChange={e => void upload(e.target.files, true)} /></label>{form.video_url && <video src={form.video_url} controls className="w-full" />}</>}
 {step === 4 && <>{field("history", "Historia cultural autorizada (opcional)")}<p>Contenido en maya pendiente de validación. No constituye certificación oficial de autenticidad.</p></>}
 {step === 5 && <>{field("price", "Precio en MXN", "number")}{field("stock", "Existencias", "number")}{field("package_weight", "Peso en kg", "number")}{field("package_dimensions", "Dimensiones en cm")}<p>Comisión: ${(Number(form.price) * .1).toFixed(2)} · Neto: ${(Number(form.price) * .9).toFixed(2)} MXN</p></>}
 {step === 6 && <>{["name", "community", "photos", "technique", "materials", "history", "audio", "video", "platform", "qr", "social"].map((k, i) => <label key={k} className="block mb-3"><input type="checkbox" checked={!!consents[`c_${k}`]} onChange={e => setConsents({ ...consents, [`c_${k}`]: e.target.checked })} /> { ["Nombre", "Comunidad", "Fotografías", "Técnica", "Materiales", "Historia", "Audio", "Video", "Publicación en plataforma", "QR", "Redes sociales"][i] }</label>)}{field("expires_at", "Vigencia opcional", "date")}<p>Nombre, fotografías, técnica, materiales y publicación son necesarios para publicar la ficha. Autoriza historia o video solo si los incluyes.</p></>}
 {step === 7 && <><img src={gallery[0]} alt={form.name} className="w-full h-48 object-cover mb-4" /><h2>{form.name}</h2><p>{form.description}</p><p>${form.price} MXN · {form.stock} piezas</p><p>El administrador revisará la publicación antes de mostrarla en el catálogo.</p></>}
 {error && <p role="alert" className="text-red-700 my-4">{error}</p>}<div className="flex gap-4 mt-6">{step > 0 && <button disabled={busy} onClick={() => setStep(step - 1)} className="btn-secondary">Atrás</button>}<button disabled={busy} onClick={() => void next()} className="btn-primary">{busy ? "Guardando…" : step === 7 ? "Enviar a revisión" : "Continuar"}</button></div></div></div>;
}
