import { Link } from "react-router";
import CraftBanner from "../components/CraftBanner";
const stages=[
 {title:"Las manos",image:"/demo/artesanos/ana.png",text:"Conoce el productor o taller y la comunidad y municipio que declara como su origen."},
 {title:"El proceso",image:"/demo/artesanos/elena.png",text:"Explora la técnica, los materiales y el proceso de elaboración que comparte el creador."},
 {title:"La pieza",image:"/demo/artesanos/lucia.png",text:"Una ficha reúne fotografías e historia autorizada para acompañar cada publicación."},
 {title:"Su conexión",image:"/demo/artesanos/mateo.png",text:"El QR enlaza a la ficha pública para que puedas consultar su información y origen."}
];
export default function Traceability(){return <div className="craft-page"><CraftBanner title="Cada pieza tiene un camino" description="Descubre cómo unimos el taller, el proceso y la historia que acompaña a una artesanía." eyebrow="Trazabilidad cultural" image="/demo/artesanos/elena.png" tone="violet"/><div className="info-container"><section className="journey-section"><span className="eyebrow">Del origen a tus manos</span><h2>Una historia que puedes seguir</h2><div className="journey-grid">{stages.map((s,i)=><article data-reveal key={s.title} className={`journey-card tone-${i}`}><div className="journey-photo"><img src={s.image} alt={s.title}/><span>{i+1}</span></div><div className="journey-copy"><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div></section><div className="trace-grid"><section data-reveal className="trace-card trace-qr"><span className="eyebrow">Un puente digital</span><h2>Código QR de trazabilidad</h2><p>Abre la ficha pública de una pieza desde su QR. Consulta su taller, materiales, historia disponible y el estado de su publicación.</p><Link className="btn-primary" to="/catalogo">Descubrir las piezas →</Link></section><section data-reveal className="trace-card trace-consent"><span className="eyebrow">La voz de quien crea</span><h2>Consentimiento cultural</h2><ul>{["El productor elige los datos y fotografías que comparte.","Autoriza la historia y el contexto de su trabajo.","Puede establecer una vigencia y retirar su consentimiento.","Decide si permite su uso en redes sociales."].map(s=><li key={s}>{s}</li>)}</ul></section></div><section className="trace-note" data-reveal><h3>Procedencia y revisión de documentos</h3><p>La información de origen es declarada y autorizada por el productor. La plataforma puede revisar el certificado aportado; esto no equivale a una certificación oficial de una institución gubernamental o cultural.</p></section><section className="trace-note language-note" data-reveal><h3>Una conexión también en maya yucateco</h3><p>Activa Maya en el header para traducir la interfaz y el contenido. Las traducciones automáticas no sustituyen la revisión de una persona hablante; el contenido cultural validado mantiene su estado en la ficha.</p></section></div></div>}
