import { useState } from "react";
import { api } from "../data/api";
import { getStore, mutate } from "../data/store";
import type { Role } from "../data/types";
export default function CertificatePanel({ role }: { role: Role }) {
 const store=getStore();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notes,setNotes]=useState<Record<string,string>>({});const [pendingOnly,setPendingOnly]=useState(false);
 const certificates=(store.certificates||[]).filter(c=>!pendingOnly||c.status==="pending").sort((a,b)=>Number(b.status==="pending")-Number(a.status==="pending"));
 async function review(id:string,status:"approved"|"rejected") { if(busy)return;setBusy(true);setError("");try{await mutate(`certificates/${id}`,"PATCH",{status,review_notes:notes[id]||""});}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
 async function replace(productId:string,file?:File){if(!file||busy)return;setBusy(true);setError("");try{const body=new FormData();body.append("file",file);const data=await api<{id:string}>("certificates","POST",body);await mutate(`products/${productId}/certificate`,"POST",{certificate_id:data.id});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const labels={pending:"Pendiente de validación",approved:"Aprobado",rejected:"Rechazado"};
 return <div><h2 className="font-display text-xl font-bold mb-3">Certificados de autenticidad</h2><p className="text-sm text-[#6B6763] mb-4">Los documentos son privados. La validación corresponde a la revisión interna de la plataforma y no sustituye una certificación oficial.</p>{role==="admin"&&<label className="block mb-4"><input type="checkbox" checked={pendingOnly} onChange={e=>setPendingOnly(e.target.checked)}/> Mostrar solo pendientes</label>}{error&&<p role="alert" className="text-red-700 mb-4">{error}</p>}{!certificates.length&&<p>No hay certificados {pendingOnly?"pendientes":"enviados"}.</p>}{certificates.map(c=><article key={c.id} className="border rounded-xl p-4 mb-4"><h3 className="font-semibold">{store.products.find(p=>p.id===c.product_id)?.name||c.product_id}</h3><p className="text-sm my-2">{labels[c.status]} · {c.original_name}</p><a className="btn-secondary text-sm" href={c.download_url} target="_blank" rel="noreferrer">Descargar certificado</a>{c.review_notes&&<p className="mt-3 text-sm">Observaciones: {c.review_notes}</p>}{c.reviewed_at&&<p className="text-xs text-[#6B6763] mt-2">Revisado: {c.reviewed_at}</p>}{role==="admin"&&c.status==="pending"&&<div className="mt-4"><label className="text-sm">Observaciones (obligatorias para rechazar)<textarea maxLength={2000} className="input-field mt-1" value={notes[c.id]||""} onChange={e=>setNotes({...notes,[c.id]:e.target.value})}/></label><div className="flex gap-3 mt-3"><button disabled={busy} className="btn-primary" onClick={()=>void review(c.id,"approved")}>Validar documento</button><button disabled={busy||!notes[c.id]?.trim()} className="btn-secondary" onClick={()=>void review(c.id,"rejected")}>Rechazar</button></div><p className="text-xs mt-2">Después de aprobar el certificado, publica la pieza desde Productos.</p></div>}{role==="producer"&&c.status==="rejected"&&<label className="block mt-4 text-sm">Enviar certificado corregido<input disabled={busy} type="file" className="block mt-2" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>void replace(c.product_id,e.target.files?.[0])}/></label>}</article>)}</div>;
}
