import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import type { Order, PaymentSandbox, Product, ProducerProfile, Role } from "../data/types";
const money=(n:number)=>n.toLocaleString("es-MX",{style:"currency",currency:"MXN"});
const statusLabels:Record<string,string>={paid:"Pagado",preparing:"Preparación",shipped:"Enviado",delivered:"Entregado",pending_payment:"Pago pendiente",refunded:"Reembolsado",cancelled:"Cancelado",return_requested:"Devolución"};
const methodLabels:Record<string,string>={card:"Tarjeta",paypal:"PayPal",transfer:"Transferencia",pending:"Pendiente"};
export default function OrderAnalytics({orders,payments,products,profiles,role}:{orders:Order[];payments:PaymentSandbox[];products:Product[];profiles:ProducerProfile[];role:Role}) {
 const completed=orders.filter(o=>["paid","preparing","shipped","delivered","return_requested"].includes(o.status));
 const counts:Record<string,number>={},methods:Record<string,number>={},ranks:Record<string,{quantity:number;amount:number}>={},workshops:Record<string,number>={};
 orders.forEach(o=>{counts[o.status]=(counts[o.status]||0)+1;});
 const allowed=new Set(completed.map(o=>o.id));
 payments.filter(p=>p.status==="approved"&&allowed.has(p.order_id)).forEach(p=>{methods[p.method]=(methods[p.method]||0)+Number(p.amount);});
 completed.forEach(o=>{workshops[o.producer_id]=(workshops[o.producer_id]||0)+Number(o.subtotal);o.items.forEach(i=>{const row=ranks[i.product_id]||{quantity:0,amount:0};row.quantity+=i.quantity;row.amount+=i.quantity*i.unit_price;ranks[i.product_id]=row;});});
 const charts=[{title:"Pedidos por estado",currency:false,data:Object.entries(counts).map(([k,value])=>({name:statusLabels[k]||k,value}))},{title:"Pagos aprobados por método",currency:true,data:Object.entries(methods).map(([k,value])=>({name:methodLabels[k]||k,value}))},...(role==="admin"?[{title:"Ventas de productos por taller",currency:true,data:Object.entries(workshops).map(([k,value])=>({name:profiles.find(p=>p.id===k)?.workshop_name||k,value}))}]:[])];
 return <div className="mt-8"><p className="text-xs text-[#6B6763] mb-4">Datos de pedidos y pagos del periodo seleccionado. Los importes aprobados excluyen pedidos cancelados, pendientes y reembolsados. Actualización automática cada 30 segundos mientras la página está visible.</p><div className="grid gap-6 md:grid-cols-2">{charts.map(chart=><section key={chart.title} className="border rounded-xl p-4 min-w-0"><h2 className="font-bold mb-4">{chart.title}</h2>{chart.data.length?<div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart.data} layout="vertical" margin={{left:10,right:15}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={chart.currency}/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:11}}/><Tooltip formatter={(value)=>chart.currency?money(Number(value)):Number(value)}/><Bar dataKey="value" name={chart.currency?"Importe MXN":"Pedidos"} fill="#B85C38"/></BarChart></ResponsiveContainer></div>:<p>Aún no hay datos en este periodo.</p>}</section>)}</div><section className="mt-6"><h2 className="font-bold mb-3">{role==="consumer"?"Artesanías compradas":"Artesanías más vendidas"}</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Producto</th><th>Piezas</th><th>Importe de productos</th></tr></thead><tbody>{Object.entries(ranks).sort((a,b)=>b[1].quantity-a[1].quantity).slice(0,10).map(([id,row])=><tr key={id} className="border-b"><td className="p-2">{products.find(p=>p.id===id)?.name||id}</td><td>{row.quantity}</td><td>{money(row.amount)}</td></tr>)}</tbody></table>{!Object.keys(ranks).length&&<p className="py-3">Aún no hay ventas pagadas.</p>}</div></section></div>;
}
