import CraftChart from "./CraftChart";
import ImageWithFallback from "./ImageWithFallback";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import type { Order, PaymentSandbox, Product, ProducerProfile, Role } from "../data/types";
const money=(n:number)=>n.toLocaleString("es-MX",{style:"currency",currency:"MXN"});
const statusLabels:Record<string,string>={paid:"Pagado",preparing:"Preparación",shipped:"Enviado",delivered:"Entregado",pending_payment:"Pago pendiente",refunded:"Reembolsado",cancelled:"Cancelado",return_requested:"Devolución"};
const methodLabels:Record<string,string>={card:"Tarjeta",paypal:"PayPal",transfer:"Transferencia",pending:"Pendiente"};
export default function OrderAnalytics({orders,payments,products,profiles,role}:{orders:Order[];payments:PaymentSandbox[];products:Product[];profiles:ProducerProfile[];role:Role}) {
 const completed=orders.filter(o=>["paid","preparing","shipped","delivered","return_requested"].includes(o.status));
 const counts:Record<string,number>={},methods:Record<string,number>={},ranks:Record<string,{quantity:number;amount:number}>={},workshops:Record<string,number>={};
 orders.forEach(o=>{counts[o.status]=(counts[o.status]||0)+1;});
 const allowed=new Set(completed.map(o=>o.id));
 payments.filter(p=>p.status==="approved"&&allowed.has(p.order_id)).forEach(p=>{methods[p.method]=(methods[p.method]||0)+Number(p.amount);});
 completed.forEach(o=>{workshops[o.producer_id]=(workshops[o.producer_id]||0)+Number(o.subtotal);o.items.forEach(i=>{const row=ranks[i.product_id]||{quantity:0,amount:0};row.quantity+=i.quantity;row.amount+=i.quantity*i.unit_price;ranks[i.product_id]=row;});});
 const charts=[{title:"Pedidos por estado",currency:false,data:Object.entries(counts).map(([k,value])=>({name:statusLabels[k]||k,value}))},{title:"Pagos aprobados por método",currency:true,data:Object.entries(methods).map(([k,value])=>({name:methodLabels[k]||k,value}))},...(role==="admin"?[{title:"Ventas de productos por taller",currency:true,data:Object.entries(workshops).map(([k,value])=>({name:profiles.find(p=>p.id===k)?.workshop_name||k,value}))}]:[])];
 return <div className="mt-8"><p className="text-xs text-[#6B6763] mb-4">Datos de pedidos y pagos del periodo seleccionado. Los importes aprobados excluyen pedidos cancelados, pendientes y reembolsados. Actualización automática cada 30 segundos mientras la página está visible.</p><div className="grid gap-6 md:grid-cols-2">{charts.map(chart=><section key={chart.title} className="analytics-card min-w-0"><div className="chart-title"><ImageWithFallback src={products[charts.indexOf(chart)]?.featured_image || "/demo/productos/cuenco.png"} alt=""/><h2 className="font-bold">{chart.title}</h2></div>{chart.data.length?<CraftChart data={chart.data} currency={chart.currency} horizontal label={chart.currency?"Importe MXN":"Pedidos"}/>:<p>Aún no hay datos en este periodo.</p>}</section>)}</div><section className="mt-6"><h2 className="font-bold mb-3">{role==="consumer"?"Artesanías compradas":"Artesanías más vendidas"}</h2><div className="ranking-list"><div>{Object.entries(ranks).sort((a,b)=>b[1].quantity-a[1].quantity).slice(0,10).map(([id,row],i)=>{const product=products.find(p=>p.id===id);return <article className="ranking-row" key={id}><span className={`rank-number rank-${i}`}>{i+1}</span><ImageWithFallback src={product?.featured_image} alt={product?.name} loading="lazy"/><div className="rank-product"><strong>{product?.name||id}</strong><span>{profiles.find(p=>p.id===product?.producer_id)?.workshop_name}</span></div><div className="rank-quantity"><b>{row.quantity}</b><small>Piezas</small></div><strong className="rank-amount" translate="no">{money(row.amount)}</strong></article>})}</div>{!Object.keys(ranks).length&&<p className="py-3">Aún no hay ventas pagadas.</p>}</div></section></div>;
}
