import { useState } from "react";
import { useApp } from "../context/AppContext";
import { getStore, mutate } from "../data/store";
export default function ProfileEditor() {
 const {user}=useApp();const p=getStore().producer_profiles.find(x=>x.user_id===user?.id);
 const [form,setForm]=useState({name:user?.name||"",phone:user?.phone||"",delivery_address:user?.delivery_address||"",delivery_postal:user?.delivery_postal||"",shipping_address:p?.shipping_address||"",workshop_name:p?.workshop_name||"",biography:p?.biography||"",community:p?.community||"",municipality:p?.municipality||"",years_experience:p?.years_experience||0,languages:(p?.languages||[]).join(", "),craft_types:(p?.craft_types||[]).join(", ")});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function save(image?:File){setBusy(true);setError("");setMessage("");try{if(image){const data=new FormData();data.append("image",image);await mutate("profile/image","POST",data);}else{await mutate("profile","PUT",{name:form.name,phone:form.phone,delivery_address:form.delivery_address,delivery_postal:form.delivery_postal,...(p?{...form,languages:form.languages.split(",").map(x=>x.trim()).filter(Boolean),craft_types:form.craft_types.split(",").map(x=>x.trim()).filter(Boolean)}:{})});}setMessage(image?"Foto actualizada.":"Perfil actualizado.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(key:keyof typeof form,label:string)=> <label className="block mb-3">{label}<input required={!["languages","craft_types","delivery_address","delivery_postal","shipping_address"].includes(key)} type={key==="years_experience"?"number":"text"} min={0} max={key==="years_experience"?100:undefined} className="input-field" value={form[key]} onChange={e=>setForm({...form,[key]:key==="years_experience"?Number(e.target.value):e.target.value})}/></label>;
 return <div className="max-w-2xl">{error&&<p role="alert" className="bg-red-50 p-3 mb-3">{error}</p>}{message&&<p role="status" className="bg-green-50 p-3 mb-3">{message}</p>}
 <div className="mb-6">{(user?.avatar_url||p?.profile_image)&&<img src={user?.avatar_url||p?.profile_image} alt="Mi foto de perfil" className="w-28 h-28 rounded-full object-cover mb-3"/>}<label className="block">Foto de perfil · JPG, PNG o WebP, máximo 5 MB<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} className="block mt-2" onChange={e=>{const f=e.target.files?.[0];if(f)void save(f);e.target.value="";}}/></label></div>
 <form onSubmit={e=>{e.preventDefault();void save();}}>{field("name","Nombre")}{field("phone","Teléfono")}{!p&&<>{field("delivery_address","Dirección de entrega")}{field("delivery_postal","Código postal")}</>}{p&&<>{field("workshop_name","Nombre del taller")}<label className="block mb-3">Biografía<textarea className="input-field" maxLength={5000} value={form.biography} onChange={e=>setForm({...form,biography:e.target.value})}/></label>{field("community","Comunidad")}{field("municipality","Municipio")}{field("shipping_address","Dirección de origen de los envíos")}{field("years_experience","Años de experiencia")}{field("languages","Idiomas separados por comas")}{field("craft_types","Artesanías separadas por comas")}</>}<button className="btn-primary" disabled={busy}>{busy?"Guardando…":"Guardar perfil"}</button></form></div>;
}
