<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Auth,DB,Hash};
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class MarketplaceController extends Controller {
 private function id(): string { return (string)Str::uuid(); }
 private function fail(string $message): never { throw ValidationException::withMessages(['form'=>$message]); }
 private function user(Request $r): User { $u=$r->user(); abort_unless($u && $u->status==='active',403); return $u; }
 private function role(Request $r,string $role): User { $u=$this->user($r); abort_unless($u->role===$role,403); return $u; }
 private function producer(Request $r): object { $u=$this->role($r,'producer'); $p=DB::table('producer_profiles')->where('user_id',$u->id)->first(); abort_unless($p,403); return $p; }
 private function notify(string $uid,string $message): void { DB::table('notifications')->insert(['id'=>$this->id(),'user_id'=>$uid,'type'=>'update','title'=>'Actualización','message'=>$message]); }
 private function audit(Request $r,string $action,string $id): void { DB::table('audit_logs')->insert(['user_id'=>$r->user()->id,'action'=>$action,'target_id'=>$id]); }
 private function rows(string $table,$query=null): array {
  return ($query??DB::table($table))->get()->map(function($x) {
   $a=(array)$x;
   foreach(['languages','craft_types','materials','gallery'] as $k) if(isset($a[$k])) $a[$k]=json_decode($a[$k],true)??[];
   foreach(['price','package_weight','rating','subtotal','shipping','total','platform_commission','producer_net','processing_cost','amount','unit_price'] as $k) if(isset($a[$k])) $a[$k]=(float)$a[$k];
   foreach(['stock','quantity','views','favorites_count','scans','years_experience'] as $k) if(isset($a[$k])) $a[$k]=(int)$a[$k];
   foreach(['active','verified_contact'] as $k) if(isset($a[$k])) $a[$k]=(bool)$a[$k];
   if(isset($a['is_read'])) {$a['read']=(bool)$a['is_read'];unset($a['is_read']);}
   if(isset($a['production_process'])) $a['process']=$a['production_process'];
   if(isset($a['transaction_id'])) $a['sandbox_transaction_id']=$a['transaction_id'];
   if(isset($a['is_simulated'])) $a['simulated']=(bool)$a['is_simulated'];
   unset($a['password'],$a['password_demo']); return $a;
  })->all();
 }
 public function state(Request $r) {
  $u=$r->user(); if($u && $u->status!=='active'){Auth::logout();$u=null;}
  $admin=$u?->role==='admin'; $pid=$u ? DB::table('producer_profiles')->where('user_id',$u->id)->value('id') : null;
  // Expired or withdrawn consent always removes cultural content and catalog availability.
  $visible=DB::table('products')->whereExists(function($q){$q->selectRaw('1')->from('cultural_consents')->whereColumn('cultural_consents.product_id','products.id')->whereNull('revoked_at')->where('allow_platform',1)->where(function($q){$q->whereNull('expires_at')->orWhere('expires_at','>',now());});});
  if(!$admin) $visible->where(fn($q)=>$q->where('status','published')->when($pid,fn($q)=>$q->orWhere('producer_id',$pid)));
  $products=$this->rows('products',$visible);
  foreach($products as &$product){$product['certificate_status']=DB::table('product_certificates')->where('product_id',$product['id'])->value('status');}unset($product); $ids=array_column($products,'id');
  $profiles=DB::table('producer_profiles');if(!$admin)$profiles->where(fn($q)=>$q->where('authorization_status','approved')->when($pid,fn($q)=>$q->orWhere('id',$pid)));
  $producers=$this->rows('producer_profiles',$profiles);
  foreach($producers as &$p){if(!$admin && $p['id']!==$pid)unset($p['shipping_address']);$p['artisan_name']=DB::table('users')->where('id',$p['user_id'])->value('name');$p['total_products']=count(array_filter($products,fn($x)=>$x['producer_id']===$p['id']));}unset($p);
  $orders=[];$payments=[];$carts=[];$favorites=[];$tickets=[];$notifications=[];$users=[];$consents=[];$logs=[];
  if($u){
   $oq=DB::table('orders');if(!$admin)$oq->where($u->role==='producer'?'producer_id':'consumer_id',$u->role==='producer'?$pid:$u->id);
   $orders=$this->rows('orders',$oq);
   foreach($orders as &$o){$o['items']=$this->rows('order_items',DB::table('order_items')->where('order_id',$o['id']));if(!$admin)unset($o['processing_cost']);if($u->role==='consumer')unset($o['platform_commission'],$o['producer_net']);}unset($o);
   $payments=$this->rows('payments',DB::table('payments')->whereIn('order_id',array_column($orders,'id')));
   $carts=$this->rows('carts',DB::table('carts')->where('consumer_id',$u->id));
   foreach($carts as &$c)$c['items']=$this->rows('cart_items',DB::table('cart_items')->where('cart_id',$c['id']));unset($c);
   $favorites=$this->rows('favorites',DB::table('favorites')->where('consumer_id',$u->id));
   $tickets=$this->rows('support_tickets',$admin?null:DB::table('support_tickets')->where('user_id',$u->id));
   $notifications=$this->rows('notifications',DB::table('notifications')->where('user_id',$u->id));
   $users=$this->rows('users',$admin?null:DB::table('users')->where('id',$u->id));
   if($admin||$pid)$consents=$this->rows('cultural_consents',$admin?null:DB::table('cultural_consents')->where('producer_id',$pid));
   if($admin)$logs=$this->rows('audit_logs',DB::table('audit_logs')->latest('id')->limit(100));
  }
  $certificates=[];
  if($admin||$pid){$cq=DB::table('product_certificates')->whereNotNull('product_id');if(!$admin)$cq->where('producer_id',$pid);$certificates=$this->rows('product_certificates',$cq);foreach($certificates as &$c){unset($c['path']);$c['download_url']='/api/certificates/'.$c['id'].'/download';}unset($c);}
  $cultural=$this->rows('cultural_records',DB::table('cultural_records')->whereIn('product_id',$ids));
  $cultural=array_values(array_filter($cultural,function($c){return DB::table('cultural_consents')->where('id',$c['consent_id'])->whereNull('revoked_at')->where(fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->exists();}));
  return response()->json(['user'=>$u,'store'=>['certificates'=>$certificates,'users'=>$users,'producer_profiles'=>$producers,'products'=>$products,'cultural_records'=>$cultural,'orders'=>$orders,'payments'=>$payments,'carts'=>$carts,'favorites'=>$favorites,'notifications'=>$notifications,'reviews'=>$this->rows('reviews',DB::table('reviews')->whereIn('product_id',$ids)->when(!$admin,fn($q)=>$q->where('status','published'))),'qr_codes'=>$this->rows('qr_codes',DB::table('qr_codes')->whereIn('product_id',$ids)),'support_tickets'=>$tickets,'consents'=>$consents,'audit_logs'=>$logs]])->header('Cache-Control','no-store');
 }
 public function login(Request $r){$v=$r->validate(['email'=>'required|email','password'=>'required|string']);$u=User::where('email',$v['email'])->where('status','active')->first();if(!$u||!Hash::check($v['password'],$u->password))$this->fail('Correo o contraseña incorrectos.');Auth::login($u);$r->session()->regenerate();$u->update(['last_login'=>now()]);return $this->state($r);}
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return response()->json(['ok'=>true]);}
 public function register(Request $r){
  $v=$r->validate(['name'=>'required|string|max:150','email'=>'required|email|max:190|unique:users,email','password'=>'required|string|min:8|max:100','phone'=>'required|string|max:30','role'=>'required|in:consumer,producer','workshop'=>'required_if:role,producer|nullable|string|max:180','workshop_desc'=>'nullable|string|max:5000','community'=>'required_if:role,producer|nullable|string|max:150','municipality'=>'required_if:role,producer|nullable|string|max:150','crafts'=>'nullable|array','crafts.*'=>'string|max:100','represented_by'=>'nullable|string|max:150','consent_platform'=>'accepted']);
  DB::transaction(function()use($v){$u=User::create(['id'=>$this->id(),'name'=>$v['name'],'email'=>$v['email'],'password'=>$v['password'],'phone'=>$v['phone'],'role'=>$v['role'],'status'=>'active']);if($v['role']==='producer')DB::table('producer_profiles')->insert(['id'=>$this->id(),'user_id'=>$u->id,'workshop_name'=>$v['workshop'],'biography'=>$v['workshop_desc']??'','community'=>$v['community'],'municipality'=>$v['municipality'],'languages'=>'["Español"]','craft_types'=>json_encode($v['crafts']??[]),'represented_by'=>$v['represented_by']??null]);});return response()->json(['ok'=>true],201);
 }
 public function cart(Request $r){$u=$this->role($r,'consumer');$v=$r->validate(['items'=>'present|array|max:100','items.*.product_id'=>'required|string|distinct|exists:products,id','items.*.quantity'=>'required|integer|min:1|max:1000']);DB::transaction(function()use($u,$v){DB::table('users')->where('id',$u->id)->lockForUpdate()->first();$id=DB::table('carts')->where('consumer_id',$u->id)->value('id') ?: 'cart_'.md5($u->id);DB::table('carts')->updateOrInsert(['id'=>$id],['consumer_id'=>$u->id,'updated_at'=>now()]);DB::table('cart_items')->where('cart_id',$id)->delete();foreach($v['items']as$i){$p=DB::table('products')->where('id',$i['product_id'])->first();if($p->status!=='published'||$p->stock<$i['quantity'])$this->fail('Producto no disponible o existencias insuficientes.');DB::table('cart_items')->insert(['cart_id'=>$id,'product_id'=>$p->id,'quantity'=>$i['quantity'],'unit_price'=>$p->price]);}});return $this->state($r);}
 public function favorite(Request $r,string $id){$u=$this->role($r,'consumer');abort_unless(DB::table('products')->where('id',$id)->where('status','published')->exists(),404);$q=DB::table('favorites')->where('consumer_id',$u->id)->where('product_id',$id);if($q->exists())$q->delete();else DB::table('favorites')->insert(['id'=>$this->id(),'consumer_id'=>$u->id,'product_id'=>$id]);return $this->state($r);}
 private function basket(Request $r,bool $lock=false): array {
  $u=$this->role($r,'consumer');$cart=DB::table('carts')->where('consumer_id',$u->id)->first();$items=$cart?DB::table('cart_items')->where('cart_id',$cart->id)->orderBy('product_id')->get():collect();if($items->isEmpty())$this->fail('Carrito vacío.');$groups=[];
  foreach($items as$i){$q=DB::table('products')->where('id',$i->product_id);$p=($lock?$q->lockForUpdate():$q)->first();$consent=DB::table('cultural_consents')->where('product_id',$p->id)->whereNull('revoked_at')->where('allow_platform',1)->where(fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->exists();if($p->status!=='published'||$p->stock<$i->quantity||!$consent)$this->fail('Una pieza ya no está disponible.');$groups[$p->producer_id][]=['product'=>$p,'quantity'=>(int)$i->quantity];}return $groups;
 }
 private function volumetric(?string $dimensions): float { if(preg_match('/^(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)$/i',str_replace(' ','',$dimensions??''),$m))return (float)$m[1]*(float)$m[2]*(float)$m[3]/5000;return 0; }
 private function shipping(array $items): int { $weight=array_sum(array_map(fn($i)=>max(0.1,(float)$i['product']->package_weight,$this->volumetric($i['product']->package_dimensions))*$i['quantity'],$items));return 130+max(0,(int)ceil($weight-1))*20; }
 public function quote(Request $r){$r->validate(['postal'=>'required|regex:/^\d{5}$/']);$groups=$this->basket($r);$shipping=array_sum(array_map(fn($items)=>$this->shipping($items),$groups));$subtotal=array_sum(array_map(fn($items)=>array_sum(array_map(fn($i)=>(int)round($i['product']->price*100)*$i['quantity'],$items)),$groups))/100;return response()->json(['shipping'=>$shipping,'subtotal'=>$subtotal,'total'=>$subtotal+$shipping,'simulated'=>true]);}
 private function buyerOrder(object $order): array { return ['id'=>$order->id,'order_number'=>$order->order_number,'status'=>$order->status,'subtotal'=>(float)$order->subtotal,'shipping'=>(float)$order->shipping,'total'=>(float)$order->total]; }
 public function checkout(Request $r){
  $u=$this->role($r,'consumer');$v=$r->validate(['address'=>'required|string|max:2000','postal'=>'required|regex:/^\d{5}$/','method'=>'required|in:card,transfer,pending,paypal','scenario'=>'required|in:approved,declined,pending','idempotency_key'=>'required|uuid']);
  return DB::transaction(function()use($r,$u,$v){
   // Lock buyer to serialize checkout retries and cart consumption.
   DB::table('users')->where('id',$u->id)->lockForUpdate()->first();
   $prior=DB::table('orders')->where('checkout_key',$v['idempotency_key'])->get();
   if($prior->isNotEmpty()){abort_unless($prior->first()->consumer_id===$u->id,403);return response()->json(['orders'=>$prior->map(fn($o)=>$this->buyerOrder($o)),'replayed'=>true]);}
   if($v['scenario']==='declined')return response()->json(['declined'=>true]);
   $groups=$this->basket($r,true);$out=[];
   foreach($groups as$pid=>$items){$subtotal=array_sum(array_map(fn($i)=>(int)round($i['product']->price*100)*$i['quantity'],$items));$shipping=$this->shipping($items)*100;$total=$subtotal+$shipping;$id=$this->id();$tx='SBX-'.$id;$paid=$v['method']!=='pending';$commission=(int)round($subtotal*.1);
    DB::table('orders')->insert(['id'=>$id,'order_number'=>'VMT-'.strtoupper(substr(str_replace('-','',$id),0,12)),'checkout_key'=>$v['idempotency_key'],'consumer_id'=>$u->id,'producer_id'=>$pid,'status'=>$paid?'paid':'pending_payment','subtotal'=>$subtotal/100,'shipping'=>$shipping/100,'total'=>$total/100,'platform_commission'=>$commission/100,'producer_net'=>($subtotal-$commission)/100,'processing_cost'=>$paid?round($total*.036+300)/100:0,'origin_address'=>DB::table('producer_profiles')->where('id',$pid)->value('shipping_address') ?: DB::table('producer_profiles')->where('id',$pid)->value('community').', '.DB::table('producer_profiles')->where('id',$pid)->value('municipality').', Quintana Roo (dirección del taller por completar)','consumer_address'=>$v['address'].', CP '.$v['postal'],'estimated_delivery'=>now()->addDays(10)->toDateString()]);
    foreach($items as$i){DB::table('order_items')->insert(['order_id'=>$id,'product_id'=>$i['product']->id,'quantity'=>$i['quantity'],'unit_price'=>$i['product']->price]);DB::table('products')->where('id',$i['product']->id)->decrement('stock',$i['quantity']);}
    DB::table('payments')->insert(['id'=>$this->id(),'order_id'=>$id,'transaction_id'=>$tx,'method'=>$v['method'],'status'=>$paid?'approved':'pending','amount'=>$total/100,'card_last_four'=>$v['method']==='card'?'4242':null,'is_simulated'=>1]);
    $this->notify($u->id,'Pedido creado: '.$id);$owner=DB::table('producer_profiles')->where('id',$pid)->value('user_id');$this->notify($owner,'Nueva venta de demostración: '.$id);$out[]=$this->buyerOrder(DB::table('orders')->where('id',$id)->first());
   }
   $cart=DB::table('carts')->where('consumer_id',$u->id)->value('id');DB::table('cart_items')->where('cart_id',$cart)->delete();return response()->json(['orders'=>$out,'tx_id'=>$tx],201);
  });
 }
 public function order(Request $r,string $id){$u=$this->user($r);$v=$r->validate(['status'=>'required|in:preparing,shipped,delivered,cancelled,return_requested,refunded','carrier'=>'nullable|string|max:100','tracking_number'=>'nullable|string|max:150']);return DB::transaction(function()use($r,$u,$v,$id){$o=DB::table('orders')->where('id',$id)->lockForUpdate()->first();abort_unless($o,404);$owner=DB::table('producer_profiles')->where('id',$o->producer_id)->value('user_id');$allowed=match($u->role){'producer'=>$owner===$u->id&&in_array($v['status'],['preparing','shipped']),'consumer'=>$o->consumer_id===$u->id&&in_array($v['status'],['delivered','return_requested','cancelled']),'admin'=>true,default=>false};abort_unless($allowed,403);
  $transitions=['paid'=>['preparing','cancelled','refunded'],'preparing'=>['shipped','cancelled','refunded'],'shipped'=>['delivered','return_requested'],'delivered'=>['return_requested'],'pending_payment'=>['cancelled'],'return_requested'=>['refunded']];if(!in_array($v['status'],$transitions[$o->status]??[]))$this->fail('Cambio de estado no permitido.');if($u->role==='consumer'&&$v['status']==='cancelled'&&$o->status!=='pending_payment')$this->fail('Solicita soporte para cancelar un pedido pagado.');
  $data=['status'=>$v['status'],'updated_at'=>now()];if($v['status']==='shipped'){if(empty($v['carrier'])||empty($v['tracking_number']))$this->fail('Captura paquetería y guía.');$data+=['carrier'=>$v['carrier'],'tracking_number'=>$v['tracking_number']];DB::table('shipments')->insert(['id'=>$this->id(),'order_id'=>$id,'carrier'=>$v['carrier'],'tracking_number'=>$v['tracking_number'],'shipped_at'=>now()]);}if($v['status']==='delivered')DB::table('shipments')->where('order_id',$id)->update(['delivered_at'=>now()]);
  if(in_array($v['status'],['cancelled','refunded'])){foreach(DB::table('order_items')->where('order_id',$id)->get()as$i)DB::table('products')->where('id',$i->product_id)->increment('stock',$i->quantity);DB::table('payments')->where('order_id',$id)->update(['status'=>$o->status==='pending_payment'?'declined':'refunded']);}
  DB::table('orders')->where('id',$id)->update($data);$this->notify($o->consumer_id,'Pedido '.$o->order_number.': '.$v['status']);$this->audit($r,'order:'.$v['status'],$id);return response()->json(['ok'=>true]);});}
 public function product(Request $r){$p=$this->producer($r);$v=$r->validate(['certificate_id'=>'required|string|max:100','name'=>'required|string|max:220','description'=>'required|string|max:10000','category'=>'required|string|max:100','price'=>'required|numeric|min:0.01|max:1000000','stock'=>'required|integer|min:0|max:100000','materials'=>'required|array','materials.*'=>'string|max:100','technique'=>'required|string|max:255','production_time'=>'nullable|string|max:100','package_weight'=>'required|numeric|min:0.1|max:1000','package_dimensions'=>'required|string|max:100','gallery'=>'required|array|min:1|max:8','gallery.*'=>'required|string|max:500','process'=>'nullable|string|max:10000','history'=>'nullable|string|max:10000','video_url'=>'nullable|string|max:500','consents'=>'required|array','consents.c_name'=>'accepted','consents.c_platform'=>'accepted','consents.c_photos'=>'accepted','consents.c_technique'=>'accepted','consents.c_materials'=>'accepted','expires_at'=>'nullable|date|after:today']);
  foreach($v['gallery']as$url)if(!str_starts_with($url,'/storage/uploads/'))$this->fail('Usa imágenes cargadas en la plataforma.');if(!empty($v['history'])&&empty($v['consents']['c_history']))$this->fail('Autoriza la historia antes de publicarla.');if(!empty($v['video_url'])&&!str_starts_with($v['video_url'],'/storage/uploads/'))$this->fail('Usa un video cargado en la plataforma.');if(!empty($v['video_url'])&&empty($v['consents']['c_video']))$this->fail('Autoriza el video.');
  DB::transaction(function()use($v,$p){$certificate=DB::table('product_certificates')->where('id',$v['certificate_id'])->where('producer_id',$p->id)->whereNull('product_id')->where('status','uploaded')->lockForUpdate()->first();if(!$certificate)$this->fail('Carga un certificado propio antes de publicar.');$id=$this->id();$cid=$this->id();$data=array_intersect_key($v,array_flip(['name','description','category','price','stock','technique','production_time','package_weight','package_dimensions']));$data+=['id'=>$id,'producer_id'=>$p->id,'status'=>'pending','materials'=>json_encode($v['materials']),'gallery'=>json_encode($v['gallery']),'featured_image'=>$v['gallery'][0]];DB::table('products')->insert($data);DB::table('product_certificates')->where('id',$certificate->id)->update(['product_id'=>$id,'status'=>'pending','updated_at'=>now()]);CertificateController::notifyAdmins($v['name'],$id);$c=['id'=>$cid,'producer_id'=>$p->id,'product_id'=>$id,'expires_at'=>$v['expires_at']??null];foreach(['name','community','photos','technique','materials','history','audio','video','platform','qr','social']as$k)$c['allow_'.$k]=!empty($v['consents']['c_'.$k]);DB::table('cultural_consents')->insert($c);DB::table('cultural_records')->insert(['id'=>$this->id(),'product_id'=>$id,'consent_id'=>$cid,'community_origin'=>$c['allow_community']?$p->community:'No autorizada','author_name'=>$p->workshop_name,'cultural_description'=>$v['history']??'','production_process'=>$v['process']??'','authorized_text'=>$v['history']??'','video_url'=>$v['video_url']??null,'disclaimer'=>'Procedencia declarada y autorizada por el productor. No constituye certificación oficial.']);$this->notify($p->user_id,'Pieza enviada a revisión.');});return response()->json(['ok'=>true],201);
 }
 public function moderateProduct(Request $r,string $id){$u=$this->user($r);$v=$r->validate(['status'=>'required|in:published,rejected,paused,pending','price'=>'sometimes|numeric|min:0.01|max:1000000','stock'=>'sometimes|integer|min:0|max:100000']);$p=DB::table('products')->where('id',$id)->first();abort_unless($p,404);$owner=DB::table('producer_profiles')->where('id',$p->producer_id)->value('user_id');abort_unless($u->role==='admin'||($owner===$u->id&&in_array($v['status'],['paused','pending'])),403);
  if($v['status']==='published'){$certificate=DB::table('product_certificates')->where('product_id',$id)->first();if($certificate && $certificate->status!=='approved')$this->fail('Aprueba primero el certificado de autenticidad.');abort_unless(DB::table('producer_profiles')->where('id',$p->producer_id)->where('authorization_status','approved')->exists(),422);abort_unless(DB::table('cultural_consents')->where('product_id',$id)->whereNull('revoked_at')->where('allow_platform',1)->where(fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->exists(),422);$qrAllowed=DB::table('cultural_consents')->where('product_id',$id)->whereNull('revoked_at')->where('allow_qr',1)->exists();if($qrAllowed)DB::table('qr_codes')->updateOrInsert(['product_id'=>$id],['id'=>$this->id(),'public_url'=>config('app.url').'/producto/'.$id.'?qr=1','active'=>1]);}
  DB::table('products')->where('id',$id)->update($v+['updated_at'=>now()]);$this->notify($owner,'Estado de publicación: '.$v['status']);$this->audit($r,'product:'.$v['status'],$id);return response()->json(['ok'=>true]);}
 public function moderateProducer(Request $r,string $id){$this->role($r,'admin');$v=$r->validate(['authorization_status'=>'required|in:approved,rejected,pending']);$p=DB::table('producer_profiles')->where('id',$id)->first();abort_unless($p,404);DB::table('producer_profiles')->where('id',$id)->update($v);if($v['authorization_status']!=='approved')DB::table('products')->where('producer_id',$id)->where('status','published')->update(['status'=>'paused']);$this->notify($p->user_id,'Perfil: '.$v['authorization_status']);$this->audit($r,'producer:'.$v['authorization_status'],$id);return response()->json(['ok'=>true]);}
 public function moderateUser(Request $r,string $id){$u=$this->role($r,'admin');abort_if($id===$u->id,422);$v=$r->validate(['status'=>'required|in:active,suspended']);$target=User::findOrFail($id);$target->update($v);if($v['status']==='suspended'){ $pid=DB::table('producer_profiles')->where('user_id',$id)->value('id');if($pid)DB::table('products')->where('producer_id',$pid)->where('status','published')->update(['status'=>'paused']);}$this->audit($r,'user:'.$v['status'],$id);return response()->json(['ok'=>true]);}
 public function upload(Request $r){$this->producer($r);$r->validate(['file'=>'required|file|mimes:jpg,jpeg,png,webp,mp4,webm|max:30720']);$path=$r->file('file')->store('uploads','public');return response()->json(['url'=>'/storage/'.$path],201);}
 public function ticket(Request $r){$u=$this->user($r);$v=$r->validate(['subject'=>'required|string|max:220','description'=>'required|string|max:10000','order_id'=>'nullable|string']);if(!empty($v['order_id']))abort_unless(DB::table('orders')->where('id',$v['order_id'])->where('consumer_id',$u->id)->exists(),403);DB::table('support_tickets')->insert($v+['id'=>$this->id(),'user_id'=>$u->id]);return response()->json(['ok'=>true],201);}
 public function ticketUpdate(Request $r,string $id){$this->role($r,'admin');$v=$r->validate(['status'=>'required|in:open,in_progress,resolved,closed']);abort_unless(DB::table('support_tickets')->where('id',$id)->exists(),404);DB::table('support_tickets')->where('id',$id)->update($v);$this->audit($r,'ticket:'.$v['status'],$id);return response()->json(['ok'=>true]);}
 public function review(Request $r){$u=$this->role($r,'consumer');$v=$r->validate(['order_id'=>'required|string','product_id'=>'required|string','rating'=>'required|integer|min:1|max:5','comment'=>'required|string|max:2000']);abort_unless(DB::table('orders')->where('id',$v['order_id'])->where('consumer_id',$u->id)->where('status','delivered')->exists()&&DB::table('order_items')->where('order_id',$v['order_id'])->where('product_id',$v['product_id'])->exists(),403);if(DB::table('reviews')->where('order_id',$v['order_id'])->where('product_id',$v['product_id'])->exists())$this->fail('Ya reseñaste esta pieza.');DB::table('reviews')->insert($v+['id'=>$this->id(),'consumer_id'=>$u->id,'consumer_name'=>$u->name]);return response()->json(['ok'=>true],201);}
 public function reviewUpdate(Request $r,string $id){$this->role($r,'admin');$v=$r->validate(['status'=>'required|in:published,rejected']);DB::table('reviews')->where('id',$id)->update($v);return response()->json(['ok'=>true]);}
 public function readNotifications(Request $r){$u=$this->user($r);DB::table('notifications')->where('user_id',$u->id)->update(['is_read'=>1]);return response()->json(['ok'=>true]);}
 public function profile(Request $r){
  $u=$this->user($r);$v=$r->validate(['name'=>'required|string|max:150','phone'=>'required|string|max:30','delivery_address'=>'sometimes|nullable|string|max:1000','delivery_postal'=>'sometimes|nullable|regex:/^\d{5}$/','shipping_address'=>'sometimes|nullable|string|max:1000','biography'=>'nullable|string|max:5000','workshop_name'=>'sometimes|required|string|max:180','community'=>'sometimes|required|string|max:150','municipality'=>'sometimes|required|string|max:150','years_experience'=>'sometimes|integer|min:0|max:100','languages'=>'sometimes|array|max:20','languages.*'=>'string|max:80','craft_types'=>'sometimes|array|max:30','craft_types.*'=>'string|max:100']);
  DB::transaction(function()use($u,$v){$u->update(array_intersect_key($v,array_flip(['name','phone','delivery_address','delivery_postal'])));if($u->role==='producer'){$fields=array_intersect_key($v,array_flip(['biography','workshop_name','community','municipality','years_experience','languages','craft_types','shipping_address']));foreach(['languages','craft_types']as$key)if(isset($fields[$key]))$fields[$key]=json_encode($fields[$key],JSON_UNESCAPED_UNICODE);if($fields)DB::table('producer_profiles')->where('user_id',$u->id)->update($fields);}});
  return response()->json(['ok'=>true]);
 }
 public function profileImage(Request $r){
  $u=$this->user($r);$r->validate(['image'=>'required|image|mimes:jpg,jpeg,png,webp|max:5120']);
  $path=$r->file('image')->store('profiles','public');$url='/storage/'.$path;
  try {DB::transaction(function()use($u,$url){$u->update(['avatar_url'=>$url]);if($u->role==='producer')DB::table('producer_profiles')->where('user_id',$u->id)->update(['profile_image'=>$url]);});}
  catch(\Throwable $e){\Illuminate\Support\Facades\Storage::disk('public')->delete($path);throw $e;}
  return response()->json(['url'=>$url],201);
 }

 public function withdraw(Request $r,string $id){$p=$this->producer($r);$c=DB::table('cultural_consents')->where('id',$id)->where('producer_id',$p->id)->first();abort_unless($c,404);DB::transaction(function()use($id,$c){DB::table('cultural_consents')->where('id',$id)->update(['revoked_at'=>now()]);DB::table('products')->where('id',$c->product_id)->update(['status'=>'paused']);DB::table('qr_codes')->where('product_id',$c->product_id)->update(['active'=>0]);});return response()->json(['ok'=>true]);}
 public function qr(Request $r,string $id){$p=$this->producer($r);$v=$r->validate(['active'=>'required|boolean']);$q=DB::table('qr_codes')->where('id',$id)->first();abort_unless($q&&DB::table('products')->where('id',$q->product_id)->where('producer_id',$p->id)->exists(),403);DB::table('qr_codes')->where('id',$id)->update($v);return response()->json(['ok'=>true]);}
 public function event(Request $r){$v=$r->validate(['product_id'=>'required|string|exists:products,id','event_type'=>'required|in:product_view,qr_scan,add_to_cart,checkout_started']);abort_unless(DB::table('products')->where('id',$v['product_id'])->where('status','published')->exists(),404);DB::table('analytics_events')->insert($v+['user_id'=>$r->user()?->id,'source'=>'web']);if($v['event_type']==='product_view')DB::table('products')->where('id',$v['product_id'])->increment('views');if($v['event_type']==='qr_scan')DB::table('qr_codes')->where('product_id',$v['product_id'])->where('active',1)->update(['scans'=>DB::raw('scans+1'),'last_scan'=>now()]);return response()->json(['ok'=>true]);}
}
